### ISSUE TITLE
i can't load the addon to blender

### ISSUE THREAD

**Issue by shaditellawi** [BlendingJake/JARCH-Vis#3]
i'm using 2.78a blender,

the addon already intalled to blender but each time i try to enable it it gives me an error

**Comment by shaditellawi** [comment]
here is the error attached
![error](https://cloud.githubusercontent.com/assets/26343653/23822751/37c85110-0664-11e7-81dd-27751e08ef1c.jpg)

**Comment by BlendingJake** [comment]
Hey, I fixed that issue and it should be ready to go. Generally, I would recommend downloading the most recent release, as I test them before I release them. Often I am working on just specific pieces of master, so I don't confirm that it all works together until right before I make a new release.
